// src/components/AccountOverview.tsx
import { useCallback, useEffect, useState } from "react";
import type { ReactElement } from "react";
import { apiRequest } from "../api";
import { formatTimeSince, isInactiveOverMonth } from "../utils/timeUtils";
import {
  buildSettingDiffRows,
  parseJsonObjectSetting,
  parseListSetting,
} from "../utils/settingDiff";
import { styles } from "../styles";
import { AccountEmailAccountsOverview } from "./AccountEmailAccountsOverview";
import { SettingDiffCell } from "./SettingDiffCell";
import { SettingDiffPopover } from "./SettingDiffPopover";
import type { DisabledUser, MailboxUser, UserStatusResponse } from "../types";

interface AccountOverviewProps {
  onEditMailbox?: (uid: string) => void;
}

type SettingKey = "apporder" | "dashboard";

interface SettingDefinition {
  key: SettingKey;
  /** used in button labels and messages */
  name: string;
  columnHeader: string;
  entryHeader: string;
  /** path segment of the per-account endpoints */
  endpoint: string;
  matches: (user: MailboxUser) => boolean;
  userValue: (user: MailboxUser) => string;
  parse: (raw: string | undefined) => Record<string, unknown> | null;
}

const SETTINGS: SettingDefinition[] = [
  {
    key: "apporder",
    name: "app order",
    columnHeader: "NC app order",
    entryHeader: "App",
    endpoint: "apporder",
    matches: (user) => Boolean(user.apporderMatches),
    userValue: (user) => user.apporder || "",
    parse: parseJsonObjectSetting,
  },
  {
    key: "dashboard",
    name: "dashboard widgets",
    columnHeader: "NC dashboard widgets",
    entryHeader: "Widget",
    endpoint: "dashboard-layout",
    matches: (user) => Boolean(user.dashboardLayoutMatches),
    userValue: (user) => user.dashboardLayout || "",
    parse: parseListSetting,
  },
];

interface DiffPopoverState {
  uid: string;
  settingKey: SettingKey;
  top: number;
  left: number;
  width: number;
}

interface PendingAction {
  uid: string;
  settingKey: SettingKey;
}

const POPOVER_MAX_WIDTH = 920;
const POPOVER_MARGIN = 8;

function isSameAction(
  action: PendingAction | null,
  uid: string,
  settingKey: SettingKey,
): boolean {
  return action?.uid === uid && action.settingKey === settingKey;
}

function AccountOverview({
  onEditMailbox,
}: AccountOverviewProps): ReactElement {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [users, setUsers] = useState<MailboxUser[]>([]);
  const [disabledUsers, setDisabledUsers] = useState<DisabledUser[]>([]);
  const [defaultApporder, setDefaultApporder] = useState("");
  const [defaultDashboardLayout, setDefaultDashboardLayout] = useState("");
  const [diffPopover, setDiffPopover] = useState<DiffPopoverState | null>(null);
  const [resetting, setResetting] = useState<PendingAction | null>(null);
  const [promoting, setPromoting] = useState<PendingAction | null>(null);
  const [promoteConfirm, setPromoteConfirm] = useState<PendingAction | null>(
    null,
  );

  const defaultValueFor = (settingKey: SettingKey): string =>
    settingKey === "apporder" ? defaultApporder : defaultDashboardLayout;

  const loadUserStatus = useCallback(async () => {
    try {
      const data = await apiRequest<UserStatusResponse>(
        OC.generateUrl("/apps/hufak/api/accounts/status"),
      );
      const nextUsers = Array.isArray(data.users) ? data.users : [];
      nextUsers.forEach((user) => {
        if (user?.identitiesLookupError) {
          console.warn(
            `[hufak] identities lookup failed for ${user.uid || "unknown"}:`,
            user.identitiesLookupError,
          );
        }
        if (user?.additionalAccountIdentitiesLookupErrors) {
          Object.entries(user.additionalAccountIdentitiesLookupErrors).forEach(
            ([account, message]) => {
              console.warn(
                `[hufak] additional account identities lookup failed for ${user.uid || "unknown"} (${account}):`,
                message,
              );
            },
          );
        }
      });
      setUsers(nextUsers);
      setDisabledUsers(
        Array.isArray(data.disabledUsers) ? data.disabledUsers : [],
      );
      setDefaultApporder(
        typeof data.defaultApporder === "string" ? data.defaultApporder : "",
      );
      setDefaultDashboardLayout(
        typeof data.defaultDashboardLayout === "string"
          ? data.defaultDashboardLayout
          : "",
      );
      setError("");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load status");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadUserStatus();
  }, [loadUserStatus]);

  useEffect(() => {
    if (!diffPopover) {
      return;
    }
    // the panel is positioned against the viewport, so any scroll or resize
    // would leave it detached from its trigger button
    const close = () => setDiffPopover(null);
    window.addEventListener("scroll", close, true);
    window.addEventListener("resize", close);
    return () => {
      window.removeEventListener("scroll", close, true);
      window.removeEventListener("resize", close);
    };
  }, [diffPopover]);

  const toggleDiffPopover = (
    uid: string,
    settingKey: SettingKey,
    anchor: HTMLElement,
  ) => {
    if (diffPopover?.uid === uid && diffPopover.settingKey === settingKey) {
      setDiffPopover(null);
      return;
    }
    const rect = anchor.getBoundingClientRect();
    const width = Math.min(
      POPOVER_MAX_WIDTH,
      window.innerWidth - 2 * POPOVER_MARGIN,
    );
    const left = Math.max(
      POPOVER_MARGIN,
      Math.min(rect.left, window.innerWidth - width - POPOVER_MARGIN),
    );
    setDiffPopover({
      uid,
      settingKey,
      top: rect.bottom + 6,
      left,
      width,
    });
  };

  const applyDefaultSetting = async (
    uid: string,
    setting: SettingDefinition,
  ) => {
    setDiffPopover(null);
    setResetting({ uid, settingKey: setting.key });
    try {
      await apiRequest(
        OC.generateUrl(
          `/apps/hufak/api/accounts/${encodeURIComponent(uid)}/${setting.endpoint}/default`,
        ),
        {
          method: "POST",
        },
      );
      await loadUserStatus();
    } catch (err) {
      setError(
        `Failed to reset ${setting.name} for ${uid}: ${err instanceof Error ? err.message : "Unknown error"}`,
      );
    } finally {
      setResetting(null);
    }
  };

  const promoteSettingToDefault = async (
    uid: string,
    setting: SettingDefinition,
  ) => {
    setDiffPopover(null);
    setPromoteConfirm(null);
    setPromoting({ uid, settingKey: setting.key });
    try {
      await apiRequest(
        OC.generateUrl(
          `/apps/hufak/api/accounts/${encodeURIComponent(uid)}/${setting.endpoint}/promote`,
        ),
        {
          method: "POST",
        },
      );
      await loadUserStatus();
    } catch (err) {
      setError(
        `Failed to set default ${setting.name} from ${uid}: ${err instanceof Error ? err.message : "Unknown error"}`,
      );
    } finally {
      setPromoting(null);
    }
  };

  if (loading) {
    return (
      <section style={styles.formSection}>
        <div style={styles.proseContent}>
          <h2>Account overview</h2>
          <p>Loading account status...</p>
        </div>
      </section>
    );
  }

  if (error) {
    return (
      <section style={styles.formSection}>
        <div style={styles.proseContent}>
          <h2>Account overview</h2>
          <p style={styles.validationMessage}>Failed to load status: {error}</p>
        </div>
      </section>
    );
  }

  const diffSetting = diffPopover
    ? SETTINGS.find((setting) => setting.key === diffPopover.settingKey)
    : undefined;
  const diffUser = diffPopover
    ? users.find((user) => user.uid === diffPopover.uid)
    : undefined;
  const diffUserRaw =
    diffSetting && diffUser ? diffSetting.userValue(diffUser) : "";
  const diffDefaultRaw = diffPopover ? defaultValueFor(diffPopover.settingKey) : "";
  const diffUserParsed = diffSetting ? diffSetting.parse(diffUserRaw) : null;
  const diffDefaultParsed = diffSetting ? diffSetting.parse(diffDefaultRaw) : null;
  const diffRows =
    diffUserParsed && diffDefaultParsed
      ? buildSettingDiffRows(diffUserParsed, diffDefaultParsed)
      : null;
  const promoteConfirmSetting = promoteConfirm
    ? SETTINGS.find((setting) => setting.key === promoteConfirm.settingKey)
    : undefined;

  return (
    <section style={styles.fullWidthSection}>
      {diffPopover && diffSetting && diffUser && (
        <SettingDiffPopover
          title={`${diffSetting.name} of ${diffUser.uid} vs. default ${diffSetting.name}`}
          entryHeader={diffSetting.entryHeader}
          userLabel={`${diffUser.uid} (user)`}
          rows={diffRows}
          userRaw={diffUserRaw}
          defaultRaw={diffDefaultRaw}
          top={diffPopover.top}
          left={diffPopover.left}
          width={diffPopover.width}
          margin={POPOVER_MARGIN}
          onClose={() => setDiffPopover(null)}
        />
      )}
      {promoteConfirm && promoteConfirmSetting && (
        <div
          style={styles.modalBackdrop}
          onMouseDown={() => setPromoteConfirm(null)}
          role="presentation"
        >
          <div
            style={styles.modalCard}
            onMouseDown={(event) => event.stopPropagation()}
          >
            <h4 style={styles.modalTitle}>
              Set new default {promoteConfirmSetting.name}
            </h4>
            <p style={styles.modalText}>
              Store the {promoteConfirmSetting.name} of{" "}
              <strong>{promoteConfirm.uid}</strong> as the new global default{" "}
              {promoteConfirmSetting.name}? It will be used for newly created
              accounts and when resetting other accounts.
            </p>
            <div style={styles.modalButtonRow}>
              <button
                type="button"
                onClick={() =>
                  promoteSettingToDefault(
                    promoteConfirm.uid,
                    promoteConfirmSetting,
                  )
                }
                style={styles.submitButton}
              >
                Set as default
              </button>
              <button
                type="button"
                onClick={() => setPromoteConfirm(null)}
                style={styles.clearButton}
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
      <div style={styles.proseSectionContent}>
        <h2>Account overview</h2>
        <p style={styles.introText}>
          Hufak-specific Nextcloud account and NextSnapMail email settings
          overview and quick-edit. To deactive and delete old accounts, use{" "}
          <a href={OC.generateUrl("/settings/users")} style={styles.inlineLink}>
            Nextcloud account management
          </a>
          .
        </p>
      </div>
      <div style={styles.tableWrapper}>
        <table style={styles.table}>
          <thead>
            <tr>
              <th style={styles.tableHeader}>UID</th>
              <th style={styles.tableHeader}>NextSnapMail email accounts</th>
              {SETTINGS.map((setting) => (
                <th key={setting.key} style={styles.tableHeader}>
                  {setting.columnHeader}
                </th>
              ))}
              <th style={styles.tableHeader}>Last activity</th>
              <th style={styles.tableHeader}>Failed login attempts</th>
            </tr>
          </thead>
          <tbody>
            {users.map((user) => (
              <tr key={user.uid}>
                <td style={styles.tableCell}>{user.uid}</td>
                <td style={{ ...styles.tableCell, ...styles.emailCell }}>
                  <div style={styles.emailCellLayout}>
                    <div style={styles.emailCellContent}>
                      <AccountEmailAccountsOverview user={user} />
                    </div>
                    {onEditMailbox ? (
                      <button
                        type="button"
                        onClick={() => onEditMailbox(user.uid)}
                        style={styles.emailCellEditButton}
                        title={`edit NextSnapMail accounts for user ${user.uid}`}
                        aria-label={`edit NextSnapMail accounts for user ${user.uid}`}
                      >
                        <span
                          className="icon icon-rename"
                          aria-hidden="true"
                          style={styles.squareIcon}
                        />
                      </button>
                    ) : null}
                  </div>
                </td>
                {SETTINGS.map((setting) => {
                  const isResetting = isSameAction(
                    resetting,
                    user.uid,
                    setting.key,
                  );
                  const isPromoting = isSameAction(
                    promoting,
                    user.uid,
                    setting.key,
                  );
                  return (
                    <td key={setting.key} style={styles.tableCell}>
                      <div style={styles.statusWithTooltip}>
                        <SettingDiffCell
                          settingName={setting.name}
                          uid={user.uid}
                          matches={setting.matches(user)}
                          busy={isResetting || isPromoting}
                          applying={isResetting}
                          promoting={isPromoting}
                          inspectExpanded={
                            diffPopover?.uid === user.uid &&
                            diffPopover.settingKey === setting.key
                          }
                          onInspect={(anchor) =>
                            toggleDiffPopover(user.uid, setting.key, anchor)
                          }
                          onApplyDefault={() =>
                            applyDefaultSetting(user.uid, setting)
                          }
                          onPromoteToDefault={() =>
                            setPromoteConfirm({
                              uid: user.uid,
                              settingKey: setting.key,
                            })
                          }
                        />
                      </div>
                    </td>
                  );
                })}
                <td style={styles.tableCell}>
                  <span>{formatTimeSince(user.lastActivityTs)}</span>
                  {user.lastActivityTs !== null &&
                    user.lastActivityTs !== undefined &&
                    Number(user.lastActivityTs) > 0 &&
                    isInactiveOverMonth(user.lastActivityTs) && (
                      <span
                        style={styles.inactiveWarning}
                        title="No activity for more than one month"
                      >
                        !
                      </span>
                    )}
                </td>
                <td style={styles.tableCell}>
                  {Number.isInteger(user.failedLoginAttempts)
                    ? user.failedLoginAttempts
                    : "-"}
                </td>
              </tr>
            ))}
            {users.length === 0 && (
              <tr>
                <td style={styles.tableCell} colSpan={4 + SETTINGS.length}>
                  No active accounts found.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
      <div style={styles.proseSectionContent}>
        <h3 style={styles.subheading}>Disabled accounts</h3>
      </div>
      <div style={styles.tableWrapper}>
        <table style={styles.table}>
          <thead>
            <tr>
              <th style={styles.tableHeader}>UID</th>
            </tr>
          </thead>
          <tbody>
            {disabledUsers.map((user) => (
              <tr key={`disabled-${user.uid}`}>
                <td style={styles.tableCell}>{user.uid}</td>
              </tr>
            ))}
            {disabledUsers.length === 0 && (
              <tr>
                <td style={styles.tableCell}>No disabled accounts found.</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </section>
  );
}

export { AccountOverview };

// src/components/AccountOverview.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { apiRequest } from '../api';
import { formatTimeSince, isInactiveOverMonth } from '../utils/timeUtils';
import {
	buildSettingDiffRows,
	parseJsonObjectSetting,
	parseListSetting,
} from '../utils/settingDiff';
import { styles } from '../styles';
import AccountEmailAccountsOverview from './AccountEmailAccountsOverview.vue';
import SettingDiffCell from './SettingDiffCell.vue';
import SettingDiffPopover from './SettingDiffPopover.vue';
import type { DisabledUser, MailboxUser, UserStatusResponse } from '../types';

const emit = defineEmits<{ (event: 'editMailbox', uid: string): void }>();

type SettingKey = 'apporder' | 'dashboard';

interface SettingDefinition {
	key: SettingKey
	/** used in button labels and messages */
	name: string
	columnHeader: string
	entryHeader: string
	/** path segment of the per-account endpoints */
	endpoint: string
	matches: (user: MailboxUser) => boolean
	userValue: (user: MailboxUser) => string
	parse: (raw: string | undefined) => Record<string, unknown> | null
}

const SETTINGS: SettingDefinition[] = [
	{
		key: 'apporder',
		name: 'app order',
		columnHeader: 'NC app order',
		entryHeader: 'App',
		endpoint: 'apporder',
		matches: (user) => Boolean(user.apporderMatches),
		userValue: (user) => user.apporder || '',
		parse: parseJsonObjectSetting,
	},
	{
		key: 'dashboard',
		name: 'dashboard widgets',
		columnHeader: 'NC dashboard widgets',
		entryHeader: 'Widget',
		endpoint: 'dashboard-layout',
		matches: (user) => Boolean(user.dashboardLayoutMatches),
		userValue: (user) => user.dashboardLayout || '',
		parse: parseListSetting,
	},
];

interface DiffPopoverState {
	uid: string
	settingKey: SettingKey
	top: number
	left: number
	width: number
}

interface PendingAction {
	uid: string
	settingKey: SettingKey
}

const POPOVER_MAX_WIDTH = 920;
const POPOVER_MARGIN = 8;

const isSameAction = (
	action: PendingAction | null,
	uid: string,
	settingKey: SettingKey,
): boolean => action?.uid === uid && action.settingKey === settingKey;

const loading = ref(true);
const error = ref('');
const users = ref<MailboxUser[]>([]);
const disabledUsers = ref<DisabledUser[]>([]);
const defaultApporder = ref('');
const defaultDashboardLayout = ref('');
const diffPopover = ref<DiffPopoverState | null>(null);
const resetting = ref<PendingAction | null>(null);
const promoting = ref<PendingAction | null>(null);
const promoteConfirm = ref<PendingAction | null>(null);

const nextcloudUsersUrl = OC.generateUrl('/settings/users');

const defaultValueFor = (settingKey: SettingKey): string =>
	settingKey === 'apporder' ? defaultApporder.value : defaultDashboardLayout.value;

const loadUserStatus = async () => {
	try {
		const data = await apiRequest<UserStatusResponse>(
			OC.generateUrl('/apps/hufak/api/accounts/status'),
		);
		const nextUsers = Array.isArray(data.users) ? data.users : [];
		nextUsers.forEach((user) => {
			if (user?.identitiesLookupError) {
				console.warn(
					`[hufak] identities lookup failed for ${user.uid || 'unknown'}:`,
					user.identitiesLookupError,
				);
			}
			if (user?.additionalAccountIdentitiesLookupErrors) {
				Object.entries(user.additionalAccountIdentitiesLookupErrors).forEach(
					([account, message]) => {
						console.warn(
							`[hufak] additional account identities lookup failed for ${user.uid || 'unknown'} (${account}):`,
							message,
						);
					},
				);
			}
		});
		users.value = nextUsers;
		disabledUsers.value = Array.isArray(data.disabledUsers) ? data.disabledUsers : [];
		defaultApporder.value = typeof data.defaultApporder === 'string' ? data.defaultApporder : '';
		defaultDashboardLayout.value =
			typeof data.defaultDashboardLayout === 'string' ? data.defaultDashboardLayout : '';
		error.value = '';
	} catch (err) {
		error.value = err instanceof Error ? err.message : 'Failed to load status';
	} finally {
		loading.value = false;
	}
};

// the panel is positioned against the viewport, so any scroll or resize would
// leave it detached from its trigger button
const closeDiffPopover = () => {
	diffPopover.value = null;
};

watch(diffPopover, (popover) => {
	if (popover) {
		window.addEventListener('scroll', closeDiffPopover, true);
		window.addEventListener('resize', closeDiffPopover);
	} else {
		window.removeEventListener('scroll', closeDiffPopover, true);
		window.removeEventListener('resize', closeDiffPopover);
	}
});

onMounted(loadUserStatus);
onBeforeUnmount(() => {
	window.removeEventListener('scroll', closeDiffPopover, true);
	window.removeEventListener('resize', closeDiffPopover);
});

const toggleDiffPopover = (uid: string, settingKey: SettingKey, anchor: HTMLElement) => {
	if (diffPopover.value?.uid === uid && diffPopover.value.settingKey === settingKey) {
		diffPopover.value = null;
		return;
	}
	const rect = anchor.getBoundingClientRect();
	const width = Math.min(POPOVER_MAX_WIDTH, window.innerWidth - 2 * POPOVER_MARGIN);
	const left = Math.max(
		POPOVER_MARGIN,
		Math.min(rect.left, window.innerWidth - width - POPOVER_MARGIN),
	);
	diffPopover.value = { uid, settingKey, top: rect.bottom + 6, left, width };
};

const applyDefaultSetting = async (uid: string, setting: SettingDefinition) => {
	diffPopover.value = null;
	resetting.value = { uid, settingKey: setting.key };
	try {
		await apiRequest(
			OC.generateUrl(
				`/apps/hufak/api/accounts/${encodeURIComponent(uid)}/${setting.endpoint}/default`,
			),
			{ method: 'POST' },
		);
		await loadUserStatus();
	} catch (err) {
		error.value = `Failed to reset ${setting.name} for ${uid}: ${err instanceof Error ? err.message : 'Unknown error'}`;
	} finally {
		resetting.value = null;
	}
};

const promoteSettingToDefault = async (uid: string, setting: SettingDefinition) => {
	diffPopover.value = null;
	promoteConfirm.value = null;
	promoting.value = { uid, settingKey: setting.key };
	try {
		await apiRequest(
			OC.generateUrl(
				`/apps/hufak/api/accounts/${encodeURIComponent(uid)}/${setting.endpoint}/promote`,
			),
			{ method: 'POST' },
		);
		await loadUserStatus();
	} catch (err) {
		error.value = `Failed to set default ${setting.name} from ${uid}: ${err instanceof Error ? err.message : 'Unknown error'}`;
	} finally {
		promoting.value = null;
	}
};

const diffSetting = computed(() =>
	diffPopover.value
		? SETTINGS.find((setting) => setting.key === diffPopover.value?.settingKey)
		: undefined,
);
const diffUser = computed(() =>
	diffPopover.value ? users.value.find((user) => user.uid === diffPopover.value?.uid) : undefined,
);
const diffUserRaw = computed(() =>
	diffSetting.value && diffUser.value ? diffSetting.value.userValue(diffUser.value) : '',
);
const diffDefaultRaw = computed(() =>
	diffPopover.value ? defaultValueFor(diffPopover.value.settingKey) : '',
);
const diffRows = computed(() => {
	const userParsed = diffSetting.value ? diffSetting.value.parse(diffUserRaw.value) : null;
	const defaultParsed = diffSetting.value ? diffSetting.value.parse(diffDefaultRaw.value) : null;
	return userParsed && defaultParsed ? buildSettingDiffRows(userParsed, defaultParsed) : null;
});
const promoteConfirmSetting = computed(() =>
	promoteConfirm.value
		? SETTINGS.find((setting) => setting.key === promoteConfirm.value?.settingKey)
		: undefined,
);
</script>

<template>
	<section v-if="loading" :style="styles.formSection">
		<div :style="styles.proseContent">
			<h2>Account overview</h2>
			<p>Loading account status...</p>
		</div>
	</section>
	<section v-else-if="error" :style="styles.formSection">
		<div :style="styles.proseContent">
			<h2>Account overview</h2>
			<p :style="styles.validationMessage">Failed to load status: {{ error }}</p>
		</div>
	</section>
	<section v-else :style="styles.fullWidthSection">
		<SettingDiffPopover
			v-if="diffPopover && diffSetting && diffUser"
			:title="`${diffSetting.name} of ${diffUser.uid} vs. default ${diffSetting.name}`"
			:entry-header="diffSetting.entryHeader"
			:user-label="`${diffUser.uid} (user)`"
			:rows="diffRows"
			:user-raw="diffUserRaw"
			:default-raw="diffDefaultRaw"
			:top="diffPopover.top"
			:left="diffPopover.left"
			:width="diffPopover.width"
			:margin="POPOVER_MARGIN"
			@close="diffPopover = null" />
		<div
			v-if="promoteConfirm && promoteConfirmSetting"
			:style="styles.modalBackdrop"
			role="presentation"
			@mousedown="promoteConfirm = null">
			<div :style="styles.modalCard" @mousedown.stop>
				<h4 :style="styles.modalTitle">Set new default {{ promoteConfirmSetting.name }}</h4>
				<p :style="styles.modalText">
					Store the {{ promoteConfirmSetting.name }} of
					<strong>{{ promoteConfirm.uid }}</strong> as the new global default
					{{ promoteConfirmSetting.name }}? It will be used for newly created accounts and
					when resetting other accounts.
				</p>
				<div :style="styles.modalButtonRow">
					<button
						type="button"
						:style="styles.submitButton"
						@click="promoteSettingToDefault(promoteConfirm.uid, promoteConfirmSetting)">
						Set as default
					</button>
					<button type="button" :style="styles.clearButton" @click="promoteConfirm = null">
						Cancel
					</button>
				</div>
			</div>
		</div>
		<div :style="styles.proseSectionContent">
			<h2>Account overview</h2>
			<p :style="styles.introText">
				Hufak-specific Nextcloud account and NextSnapMail email settings overview and
				quick-edit. To deactive and delete old accounts, use
				<a :href="nextcloudUsersUrl" :style="styles.inlineLink">Nextcloud account management</a>.
			</p>
		</div>
		<div :style="styles.tableWrapper">
			<table :style="styles.table">
				<thead>
					<tr>
						<th :style="styles.tableHeader">UID</th>
						<th :style="styles.tableHeader">NextSnapMail email accounts</th>
						<th v-for="setting in SETTINGS" :key="setting.key" :style="styles.tableHeader">
							{{ setting.columnHeader }}
						</th>
						<th :style="styles.tableHeader">Last activity</th>
						<th :style="styles.tableHeader">Failed login attempts</th>
					</tr>
				</thead>
				<tbody>
					<tr v-for="user in users" :key="user.uid">
						<td :style="styles.tableCell">{{ user.uid }}</td>
						<td :style="{ ...styles.tableCell, ...styles.emailCell }">
							<div :style="styles.emailCellLayout">
								<div :style="styles.emailCellContent">
									<AccountEmailAccountsOverview :user="user" />
								</div>
								<button
									type="button"
									:style="styles.emailCellEditButton"
									:title="`edit NextSnapMail accounts for user ${user.uid}`"
									:aria-label="`edit NextSnapMail accounts for user ${user.uid}`"
									@click="emit('editMailbox', user.uid)">
									<span class="icon icon-rename" aria-hidden="true" :style="styles.squareIcon" />
								</button>
							</div>
						</td>
						<td v-for="setting in SETTINGS" :key="setting.key" :style="styles.tableCell">
							<div :style="styles.statusWithTooltip">
								<SettingDiffCell
									:setting-name="setting.name"
									:uid="user.uid"
									:matches="setting.matches(user)"
									:busy="isSameAction(resetting, user.uid, setting.key) || isSameAction(promoting, user.uid, setting.key)"
									:applying="isSameAction(resetting, user.uid, setting.key)"
									:promoting="isSameAction(promoting, user.uid, setting.key)"
									:inspect-expanded="diffPopover?.uid === user.uid && diffPopover?.settingKey === setting.key"
									@inspect="toggleDiffPopover(user.uid, setting.key, $event)"
									@apply-default="applyDefaultSetting(user.uid, setting)"
									@promote-to-default="promoteConfirm = { uid: user.uid, settingKey: setting.key }" />
							</div>
						</td>
						<td :style="styles.tableCell">
							<span>{{ formatTimeSince(user.lastActivityTs) }}</span>
							<span
								v-if="user.lastActivityTs !== null && user.lastActivityTs !== undefined && Number(user.lastActivityTs) > 0 && isInactiveOverMonth(user.lastActivityTs)"
								:style="styles.inactiveWarning"
								title="No activity for more than one month">!</span>
						</td>
						<td :style="styles.tableCell">
							{{ Number.isInteger(user.failedLoginAttempts) ? user.failedLoginAttempts : '-' }}
						</td>
					</tr>
					<tr v-if="users.length === 0">
						<td :style="styles.tableCell" :colspan="4 + SETTINGS.length">
							No active accounts found.
						</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div :style="styles.proseSectionContent">
			<h3 :style="styles.subheading">Disabled accounts</h3>
		</div>
		<div :style="styles.tableWrapper">
			<table :style="styles.table">
				<thead>
					<tr>
						<th :style="styles.tableHeader">UID</th>
					</tr>
				</thead>
				<tbody>
					<tr v-for="user in disabledUsers" :key="`disabled-${user.uid}`">
						<td :style="styles.tableCell">{{ user.uid }}</td>
					</tr>
					<tr v-if="disabledUsers.length === 0">
						<td :style="styles.tableCell">No disabled accounts found.</td>
					</tr>
				</tbody>
			</table>
		</div>
	</section>
</template>
