// src/components/MailboxCredentialsFields.tsx
import type { ReactElement } from 'react';
import { styles } from '../styles';

interface MailboxCredentialsFieldsProps {
	label: string
	emailId: string
	passwordId: string
	emailName: string
	passwordName: string
	email: string
	password: string
	onEmailChange: (value: string) => void
	onPasswordChange: (value: string) => void
	disabled?: boolean
	emailPlaceholder?: string
	passwordPlaceholder?: string
	emailSuggestions?: string[]
}

function MailboxCredentialsFields({
	label,
	emailId,
	passwordId,
	emailName,
	passwordName,
	email,
	password,
	onEmailChange,
	onPasswordChange,
	disabled = false,
	emailPlaceholder = 'e-mail',
	passwordPlaceholder = 'Password',
	emailSuggestions = [],
}: MailboxCredentialsFieldsProps): ReactElement {
	const emailSuggestionsId = emailSuggestions.length > 0 ? `${emailId}-suggestions` : undefined;

	return (
		<>
			<label style={styles.fieldLabel} htmlFor={emailId}>
				{label}
			</label>
			<div style={styles.mailboxRow}>
				<input
					id={emailId}
					type="email"
					value={email}
					onChange={(event) => onEmailChange(event.target.value)}
					autoComplete="off"
					name={emailName}
					disabled={disabled}
					placeholder={emailPlaceholder}
					aria-label="email"
					list={emailSuggestionsId}
					style={{ ...styles.input, ...styles.addUserInput, maxWidth: 'none', minWidth: 0 }}
				/>
				{emailSuggestionsId && (
					<datalist id={emailSuggestionsId}>
						{emailSuggestions.map((suggestion) => (
							<option key={suggestion} value={suggestion} />
						))}
					</datalist>
				)}
				<div className="hufak-mailbox-password-row">
					<input
						id={passwordId}
						type="password"
						value={password}
						onChange={(event) => onPasswordChange(event.target.value)}
						autoComplete="new-password"
						name={passwordName}
						disabled={disabled}
						placeholder={passwordPlaceholder}
						aria-label="password"
						style={{ ...styles.input, ...styles.addUserInput, maxWidth: 'none', minWidth: 0, margin: 0 }}
					/>
					<p className="hufak-mailbox-password-note" style={{ ...styles.hintText, margin: 0 }}>
						(copy password over from{' '}
						<a
							href="https://kas.all-inkl.com/email/email-account/"
							target="_blank"
							rel="noreferrer"
							style={styles.inlineLink}
						>
							kas.all-inkl.com
						</a>
						)
					</p>
				</div>
			</div>
		</>
	);
}

export { MailboxCredentialsFields };

// src/components/MailboxCredentialsFields.vue
<script setup lang="ts">
import { computed } from 'vue';
import { styles } from '../styles';

const props = withDefaults(
	defineProps<{
		label: string
		emailId: string
		passwordId: string
		emailName: string
		passwordName: string
		email: string
		password: string
		disabled?: boolean
		emailPlaceholder?: string
		passwordPlaceholder?: string
		emailSuggestions?: string[]
	}>(),
	{
		disabled: false,
		emailPlaceholder: 'e-mail',
		passwordPlaceholder: 'Password',
		emailSuggestions: () => [],
	},
);

const emit = defineEmits<{
	(event: 'update:email', value: string): void
	(event: 'update:password', value: string): void
}>();

const emailSuggestionsId = computed(() =>
	props.emailSuggestions.length > 0 ? `${props.emailId}-suggestions` : undefined,
);
const emailInputStyle = { ...styles.input, ...styles.addUserInput, maxWidth: 'none', minWidth: 0 };
const passwordInputStyle = { ...emailInputStyle, margin: 0 };
const passwordNoteStyle = { ...styles.hintText, margin: 0 };
</script>

<template>
	<label :style="styles.fieldLabel" :for="emailId">{{ label }}</label>
	<div :style="styles.mailboxRow">
		<input
			:id="emailId"
			type="email"
			:value="email"
			autocomplete="off"
			:name="emailName"
			:disabled="disabled"
			:placeholder="emailPlaceholder"
			aria-label="email"
			:list="emailSuggestionsId"
			:style="emailInputStyle"
			@input="emit('update:email', ($event.target as HTMLInputElement).value)">
		<datalist v-if="emailSuggestionsId" :id="emailSuggestionsId">
			<option v-for="suggestion in emailSuggestions" :key="suggestion" :value="suggestion" />
		</datalist>
		<div class="hufak-mailbox-password-row">
			<input
				:id="passwordId"
				type="password"
				:value="password"
				autocomplete="new-password"
				:name="passwordName"
				:disabled="disabled"
				:placeholder="passwordPlaceholder"
				aria-label="password"
				:style="passwordInputStyle"
				@input="emit('update:password', ($event.target as HTMLInputElement).value)">
			<p class="hufak-mailbox-password-note" :style="passwordNoteStyle">
				(copy password over from
				<a
					href="https://kas.all-inkl.com/email/email-account/"
					target="_blank"
					rel="noreferrer"
					:style="styles.inlineLink">kas.all-inkl.com</a>)
			</p>
		</div>
	</div>
</template>
