// src/components/SignaturePreview.vue
<script setup lang="ts">
import { computed } from 'vue';
import { styles } from '../styles';

const props = defineProps<{ signature: string }>();

const htmlContent = computed(() =>
	props.signature.startsWith(':HTML:') ? props.signature.slice(6) : null,
);
</script>

<template>
	<div
		v-if="htmlContent !== null"
		class="hufak-signature-preview-html"
		:style="styles.signaturePreviewHtml"
		v-html="htmlContent" />
	<pre v-else :style="styles.signaturePreviewPre">{{ signature }}</pre>
</template>

// src/components/SignaturePreview.tsx
import type { ReactElement } from 'react';
import { styles } from '../styles';

interface SignaturePreviewProps {
	signature: string
}

function SignaturePreview({ signature }: SignaturePreviewProps): ReactElement {
	if (signature.startsWith(':HTML:')) {
		const htmlContent = signature.slice(6);
		return (
			<div
				className="hufak-signature-preview-html"
				style={styles.signaturePreviewHtml}
				dangerouslySetInnerHTML={{ __html: htmlContent }}
			/>
		);
	}

	return (
		<pre style={styles.signaturePreviewPre}>
			{signature}
		</pre>
	);
}

export { SignaturePreview };
